# This workflow will perform a compilation test on 
# each push to the branch master to check its correct 
# compilation and will deliver an artifact to check 
# if the change is working properly.
name: FlamePaper Build (master)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # The corresponding tests are performed in the versions
    # marked as Long Term Support by Oracle and in its
    # latest version up to the moment.
    strategy:
      matrix:
        java: [8]

    steps:
    # Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Setup a version of the Java JDK
    - name: Setup JAVA ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        architecture: x64

    # The corresponding dependencies are stored in the cache to speed up the test.
    - name: Cache Maven Packages
      uses: actions/cache@v2.1.7
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # Start building FlamePaper
    - name: Build FlamePaper
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        ./build.sh
    # An artifact is generated in a compressed file according to each JDK build version.
    - name: Upload FlamePaper Server
      uses: actions/upload-artifact@v3
      with:
        name: FlamePaper-Server
        path: FlamePaper-Server/target/FlamePaper.jar

    - name: Upload FlamePaper API
      uses: actions/upload-artifact@v3
      with:
        name: FlamePaper-API
        path: FlamePaper-API/target/flamepaper-api-1.8.8-R0.1-SNAPSHOT.jar
